# Generated by Django 5.0.2 on 2024-06-14 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tittle',
            new_name='title',
        ),
    ]
